$(document).ready(function(){
	$("#menubar").on("click",function(){
		$(".menus").click(function(){
			$(".menus").css("background-color","");
			$(this).css("background-color","red");
			$("#menubar").off("click");
		})
	})
})